# Generated by Django 2.2.5 on 2020-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('slug', models.SlugField(default='slug', unique=True)),
            ],
        ),
    ]
