# Generated by Django 2.2.5 on 2020-03-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
